### ISSUE TITLE
Allow passing environment variables

### ISSUE THREAD

**Issue by siebz0r** [siebz0r/moby#3]
Allow passing environment variables to the container by allowing it in the config:

```yaml
envlist: [test]

test:
  run:
    - echo $BIRD
  passenv:
    BIRD
```

This should allow a user to pass an environment variable on the command line:
```bash
BIRD=word moby
```
